version: "3"
services:
    safe-place-db:
        container_name: safe-place-db
        image: kimwithglasses/safe-place-db:0.0.1
        ports:
          - 3305:3306        

    safe-place-api:
        container_name: safe-place-api
        image: kimwithglasses/safe-place-api:0.0.1
        restart: on-failure:10
        #build: .
        ports:
          - 80:8080
        depends_on:
          - safe-place-db