spring:
  session:
    store-type: redis
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3305/safe_place?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  redis:
    host: localhost
    #password:
    port: 6379
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR