spring:
  datasource:
    username: root
    password: root
    #TEST
    url: jdbc:mysql://localhost:3306/moBack?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR