spring:
  datasource:
    username: root
    password: root
    #DEPLOY
    url: jdbc:mysql://safe-place-db:3306/moBack?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR