version: "3"
services:
    safe-place-db:
        container_name: safe-place-db
        image: mysql:8.0.21
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=moBack
            - MYSQL_USER=root
            - MYSQL_PASSWORD=root
        ports:
          - 3305:3306        

    safe-place-api:
        build: .
        ports:
          - 80:8080
        depends_on:
          - safe-place-db