spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/safe_place?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL56SpatialDialect
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR
